AllCops:
  TargetRubyVersion: 2.4

Style/Documentation:
  Enabled: false

# Avoid complex methods.
Metrics/CyclomaticComplexity:
  Max: 9

Metrics/LineLength:
  Max: 120
  # To make it possible to copy or click on URIs in the code, we allow lines
  # containing a URI to be longer than Max.
  AllowHeredoc: true
  AllowURI: true
  URISchemes:
    - http
    - https

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 20

Metrics/BlockLength:
  CountComments: false  # count full line comments?
  Max: 25
  ExcludedMethods: []
  Exclude:
    - spec/**/*

Metrics/ParameterLists:
  Max: 10
  CountKeywordArgs: true

Metrics/PerceivedComplexity:
  Max: 7
