# frozen_string_literal: true

source 'https://rubygems.org'

ruby '2.4.1'

group :development, :test do
  gem 'byebug',                 platforms: %i[mri mingw x64_mingw]
  gem 'colorize',               '~> 0.8.1'
  gem 'rspec',                  '~> 3.7'
  gem 'thor',                   '~> 0.20.0'
end
