# frozen_string_literal: true

source 'https://rubygems.org'

ruby '2.4.1'

group :development, :test do
  gem 'byebug',                 platforms: %i[mri mingw x64_mingw]
  gem 'rspec',                  '~> 3.7'
end
